

#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: yeleywale

# Short bio or description (displayed in the header)
description: Hi I'm Akinwale Awoyele, a computer programmer and journeyman software engineer living in Lagos , Nigeria. I code for fun and profit. I'm also likely to be caught touring the great continent of Africa, whether rappeling across canyons in Cape Town or searching through the ancient ruins in Timbuktu.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/2574957?s=400&u=12bb8593d157fba19756289afed6f72ed2b829bf&v=4

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: yeleywale@gmail.com
  facebook:
  flickr:
  github: yeleywale
  instagram:
  linkedin: https://linkedin.com/in/yeleywale
  pinterest:
  rss: akinwale
  twitter: yeleywale
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: http://disqus.com/by/ibanka 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://www.wale.ninja

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :compressed # You might prefer to minify using :compressed
  
# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-seo-tag
  - jekyll-feed 
  - jekyll-toc

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

encoding: utf-8


